// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Call struct {
	IDCall              int64     `json:"id_call"`
	Origin              int32     `json:"origin"`
	Destination         int32     `json:"destination"`
	PartNumber          string    `json:"part_number"`
	Operation           int32     `json:"operation"`
	EmployeeID          int32     `json:"employee_id"`
	Setup               bool      `json:"setup"`
	Urgent              bool      `json:"urgent"`
	CreatedAt           time.Time `json:"created_at"`
	ClosedAt            time.Time `json:"closed_at"`
	QualDescription     string    `json:"qual_description"`
	QualCheckID         int32     `json:"qual_check_id"`
	QualCheckDatetimeAt time.Time `json:"qual_check_datetime_at"`
	EngDescription      string    `json:"eng_description"`
	EngCheckID          int32     `json:"eng_check_id"`
	EngCheckDatetimeAt  time.Time `json:"eng_check_datetime_at"`
	LogDescription      string    `json:"log_description"`
	LogCheckID          int32     `json:"log_check_id"`
	LogCheckDatetimeAt  time.Time `json:"log_check_datetime_at"`
	ManDescription      string    `json:"man_description"`
	ManCheckID          int32     `json:"man_check_id"`
	ManCheckDatetimeAt  time.Time `json:"man_check_datetime_at"`
	Company             string    `json:"company"`
}

type User struct {
	IDUser   int32  `json:"id_user"`
	NameUser string `json:"name_user"`
	Sector   string `json:"sector"`
	Company  string `json:"company"`
}
